name       : perl-class-tiny
version    : '1.008'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.008.tar.gz : ee058a63912fa1fcb9a72498f56ca421a2056dc7f9f4b67837446d6421815615
homepage   : https://metacpan.org/pod/Class::Tiny
license    : Apache-2.0
component  : programming.perl
summary    : Class::Tiny - Minimalist class construction
description: |
    Class::Tiny - Minimalist class construction
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
