name       : perl-class-tiny
version    : 1.006
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Class-Tiny-1.006.tar.gz : 2efcbd31528be51d3022c616768558b78c6172df5f03c5dc698939f65488cb4e
license    : Apache-2.0
component  : programming.perl
summary    : Class::Tiny - Minimalist class construction
description: |
    Class::Tiny - Minimalist class construction
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
